### ISSUE TITLE
CI/CD online

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.android#1]
As a NOI App developer I want to have the CI/CD infrastructure online in order to be faster in the release and test of new versions of the app

- [x] Dimension provides a hello-world to get started with the pipelines
- [x] NOI creates a CI pipeline with public feedback logs
- [x] NOI creates a CD pipeline to build and push the app to a test channel
  - [x] First release on the internal test channel (needs to be manual for first release, because we need to get a `packagename` first)
  - [x] Update README
  - [x] Create a second release via pipeline <-- need to wait for Google to approve the first manual test release
- [x] @alexlanz we need to update this pipeline already --> switch to Android App Bundle (no APK anymore) --> see email for details
- [x] The first version of the app deployment to the test channel failed --> https://github.com/noi-techpark/it.bz.noi.community.android/runs/3661776178?check_suite_focus=true
- [x] Autoinc the build number with EPOCH seconds (do not commit back to git)
- [x] Write documentation

**Comment by Piiit** [comment]
Internal testing worked, it was automatically installed to the corresponding play store channel
![photo_2021-08-12_20-22-27](https://user-images.githubusercontent.com/6096063/129248708-3a82be4d-a561-4f24-9934-016096ab33cd.jpg)

**Comment by Piiit** [comment]
@sseppi I invited Alex to this party, to solve the App Bundle issue... due to my absence the next two weeks.

**Comment by Piiit** [comment]
@alexlanz The deployment failed... see https://github.com/noi-techpark/it.bz.noi.community.android/runs/3470829818?check_suite_focus=true

**Comment by alexlanz** [comment]
This should work now. There was just an error, because the version number already exists in Google Play and so you have to bump the version up.

**Comment by stezan** [comment]
yeah that's true, the version has to be manually bumped from the code. Automatically updating it from CI/CD is not recommended
