### ISSUE TITLE
Login - being asked every single time I access the app

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.android#108]
Every single time I open the app, it asks me to do the login. I thought I would stay logged in automatically once having the app installed and having done the first login.

- Android Version: 11
- Language of your application: `de`
- Phone: Samsung Galaxy A40
- Application version: 0.1.0.1652364224

**Comment by Piiit** [comment]
@MarE1991 We incremented the timeout now, please test again and see if it good enough like this

**Comment by Piiit** [comment]
@sseppi FYI

**Comment by MarE1991** [comment]
> @MarE1991 We incremented the timeout now, please test again and see if it good enough like this

@Piiit great, now it seems to work for a couple of days, should be fine for now. Thank you!
