### ISSUE TITLE
Push Notification Detail Page not showing

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.noi.community.android#112]
**Describe the bug**
The push message is delivered on the phone but the Detail page is not opening with the send news. (Tested with ID: 		"link": "noi-community://it.bz.noi.community/newsDetails/B5159512-A6E7-42C6-8792-1E947B3531A7")

**To Reproduce**
1. Push Message has to be sent
2. Open the push message

**Expected behavior**
The Detail page of the according news should be opened

**Please complete the following information:**
- Android Version: 12
- Language of your application:  `de`
- Phone: Samsung Galaxy A52S
- Application version (0.1.0.1655188998)

**Comment by chiaraDimension** [comment]
There was a bug in the Android manifest. The PR #116 fixes it.
