### ISSUE TITLE
Google Maps Link not working

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.noi.community.android#114]
**Describe the bug**
The google maps link inside Meet / Detailview -- Maps Button does not work, it always shows "Download google maps or waze...."

**To Reproduce**
1. Go to 'Meet'
2. Click on 'a Detailview of a record'
3. click on 'the button maps'
4. See message

**Expected behavior**
Google Maps should open or a dialog to ask which map application if more are available

**Please complete the following information:**
- Android Version: 12
- Language of your application:  `de`
- Phone: Xiaomi 10 Lite
- Application version (you find it in the `More` section under the NOI logo): 0.1.0.1655188998

**Comment by chiaraDimension** [comment]
The method used to find the address with an external map (i.e. Google Maps) requires additional permissions with Android 11+. The issue will be solved by the PR #117.
