### ISSUE TITLE
Android Deployment not working

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.noi.community.android#131]
I needed to change the authserver domain from bz.it to .com, but the deployment did not work anymore
`Uploading app/build/outputs/bundle/productionRelease/app-production-release.aab
##[error***Error: Your app currently targets API level 30 and must target at least API level 31.
##[error***Your app currently targets API level 30 and must target at least API level 31.`
so i tried to change the ragedSdk version https://github.com/noi-techpark/it.bz.noi.community.android/commit/6ad04c7066f976e2f2317892c6e098eb035824fa
But now i get errors on the unit tests.......(https://github.com/noi-techpark/it.bz.noi.community.android/actions/runs/3713968874/jobs/6297369704)

@chiaraDimension any suggestions?

**Comment by chiaraDimension** [comment]
Hi @RudiThoeni,
the migration from Android 11 (API level 30) to Android 12 (API level 31) implies at least some other changes in AndroidManifest.xml file, as you can read [here](https://developer.android.com/google/play/requirements/target-sdk). I try to fix and I let you know.
