### ISSUE TITLE
Instrumentation test pipeline fails because of Glide library

### ISSUE THREAD

**Issue by stezan** [noi-techpark/it.bz.noi.community.android#18]
https://github.com/DimensionSrl/it.bz.noi.community.android/runs/3620111095?check_suite_focus=true
The pipeline fails because it can not find the Glide library `com.github.bumptech.glide:glide:4.12.0`

Glide is a very common Android library for asynchronously download images from URLs. Do you know which could be the problem with the pipeline?

The Glide version is correct https://github.com/bumptech/glide/releases

@Piiit

**Comment by Piiit** [comment]
@alexlanz please have a look.. thx

**Comment by alexlanz** [comment]
Is this issues still open? Because I saw that you made also some commits afterwards that where green again: https://github.com/DimensionSrl/it.bz.noi.community.android/commits/feature/app-skeleton

**Comment by alexlanz** [comment]
Otherwise, I think this could help: https://github.com/bumptech/glide/issues/2993

**Comment by stezan** [comment]
Now it works, I think we can close this comment
