### ISSUE TITLE
App languages

### ISSUE THREAD

**Issue by chiaraDimension** [noi-techpark/it.bz.noi.community.android#20]
@sseppi Which languages should we provide for the app? Will it be only in English or in three languages (English - Italian - German)?

cc @Piiit, @RudiThoeni

**Comment by sseppi** [comment]
@chiaraDimension I've asked our communication and they told me that the app should be in three languages.

The idea could be that the app will take per default the language of the operating system (if Italian, German or English) or English in case that the Operating System language is another one. The user should have in any case the possibility to change the language settings in the general settings of the App.

Our communication asked us if we can ask the user to choose the language at the first login.

**Comment by macteo** [comment]
> The user should have in any case the possibility to change the language settings in the general settings of the App.

This is not how the user expects the apps to work and technically its not easy to require this setting to be changed at runtime (it's fighting against the operating systems). So eventually I'll put it in a following MVP if the request arises.

Furthermore iOS let you override the language setting on a per-app basis in the system provided Settings app.
