### ISSUE TITLE
Solve Play Store update issues

### ISSUE THREAD

**Issue by macteo** [noi-techpark/it.bz.noi.community.android#40]
@Piiit I think that the automatic update failures are due to the _unreviewed_ status of the app.

I would suggest you to publish the app on a Closed testing track (even one without any tester list enabled) and let Google review it. 

This should let the app be listed on the Play Store for internal testers and allow automatic updates of the app as soon as a new build is published.

**Comment by Piiit** [comment]
![Selection_121](https://user-images.githubusercontent.com/6096063/136567086-88317776-0683-4a54-8d6c-34df9e65feb9.png)

We need to wait for Google now

**Comment by Piiit** [comment]
This is still not working as it should, I have to manually delete and re-install the app to get an updated version... maybe we need to provide always a new version string, not just the build number... However, for Dimension this task is considered DONE... I will investigate when we start to have a broader test community

**Comment by Piiit** [comment]
@macteo @chiaraDimension @MarE1991 @sseppi Tested also the new version string, still the same... I need to uninstall and reinstall the app from the link. It also takes approx. 2 days to get then the new version. That is not satisfactory... maybe we should look into another way to provide test versions. Firebase eventually?

**Comment by Piiit** [comment]
I think this can be closed, either we switch to another distribution mechanism or we should just be patient to wait releases as they are at the moment...
