### ISSUE TITLE
Localization of /v1/EventShort/RoomMapping

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community.android#50]
At the moment the service `/v1/EventShort/RoomMapping` just returns a map with key (`AnchorVenueRoomMapping`) to  the Italian map url value. The service needs to be updated in order to support localisation (it, en, de)

E.g.

Actual response
```json
{
  "NOISE": "https://maps.noi.bz.it/?shared=A1-0-37",
  // ...
}
```

Suggested solution

```json
{
  "NOISE": {
  	"it": "https://maps.noi.bz.it/?shared=A1-0-37",
  	"de": "https://maps.noi.bz.it/de/?shared=A1-0-37",
  	"en": "https://maps.noi.bz.it/en/?shared=A1-0-37"
  },
  // ...
}
```

**Comment by Piiit** [comment]
@RudiThoeni The new maps website would be like this:

```json
"NOISE": {
  	"it": "https://maps.noi.bz.it/en/?shared=A1-0-37",
  	"de": "https://maps.noi.bz.it/de/?shared=A1-0-37",
  	"en": "https://maps.noi.bz.it/en/?shared=A1-0-37"
  },
```

It redirects to "/en" with the new map version, if the language in the URL is missing

**Comment by Piiit** [comment]
@chiaraDimension We found out that Github does not allow it to be added from you directly within the issue, but you can simply go to the Kanban board, and add it from there...
