### ISSUE TITLE
Section "Eat" - the problem with the crashing of the app when trying to tap on any "MENU" button continues to exist

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.android#52]
- [x] I downloaded the new version as we said during our sprint meeting, but unfortunately, whenever I try to tap on the MENU button of any of the three restaurants, the app crashes.
- [x] Moreover, could you please change the order of the three restaurants? The first one should be NOI-COMMUNITY BAR (written with a hyphen between), then NOISTERIA and then ALUMIX

German Version
Samsung Galaxy A40

**Comment by Piiit** [comment]
@mare1991 @chiaraDimension I think the automatic update isn't working... the new version should be 0.1.0.1634049426, please try again to install the Alpha version from https://play.google.com/store/apps/details?id=it.bz.noi.community

**Comment by chiaraDimension** [comment]
> Hello @chiaraDimension
> with the help of @Piiit I managed to finally download the new version and now everything works out as it should. So I guess we can close this issue!

Super!

@Piiit the PR #54 is ready to be merged. It fixes point 2 of this issue. Thank you
