### ISSUE TITLE
Integrate firebase crashlytics

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community.android#56]

**Comment by Piiit** [comment]
@chiaraDimension Perfect, thanks... I will test and let you know

**Comment by Piiit** [comment]
@chiaraDimension CI fails... https://github.com/noi-techpark/it.bz.noi.community.android/runs/4093743031?check_suite_focus=true

**Comment by chiaraDimension** [comment]
> @chiaraDimension CI fails... https://github.com/noi-techpark/it.bz.noi.community.android/runs/4093743031?check_suite_focus=true

Sorry, we missed to restore google-services.json injection step (see PR #69 )
