### ISSUE TITLE
NOI Maps

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.android#7]
Related to https://github.com/noi-techpark/it.bz.noi.community/issues/7 (not blocking)

As an app user I want to find information about where are located all services (es. restaurants, meeting rooms, etc.), companies, laboratories and institution in the park in order to find them easily.​
The data are made available through the Open Data Hub API:

Useful link for the development:
- web application: https://maps.noi.bz.it/
- web component: https://webcomponents.opendatahub.bz.it/webcomponent/9232cce6-2f39-11eb-adc1-0242ac120002
- swagger: https://swagger.opendatahub.bz.it/?url=https://mobility.api.opendatahub.bz.it/v2/apispec
- API call example: https://mobility.api.opendatahub.bz.it/v2/flat/NOI-Place?limit=-1&offset=0&select=sname,smetadata&where=smetadata.building_code.neq.null,smetadata.building_name.neq.null,sorigin.eq.office365

**Comment by Piiit** [comment]
@chiaraDimension Please change the map URLS to this --> https://maps.noi.bz.it/en/?fullview=1&hidezoom=1 (depending on each language)... that should remove the cookie banner, zoom icons and title... thank you

**Comment by chiaraDimension** [comment]
@Piiit the URL is already https://maps.noi.bz.it/en/?fullview=1&hidezoom=1 (depending on each language), but the parameters don't work yet (see https://github.com/noi-techpark/it.bz.noi.community.android/pull/45)

**Comment by Piiit** [comment]
@chiaraDimension I deployed the new version 20 minutes ago, maybe you need to clear the cache to see the updated web site?

**Comment by Piiit** [comment]
@chiaraDimension It works on my phone... cool :+1:
