### ISSUE TITLE
Better title in application menus 

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.android#73]
Sometimes the title in the application menu is truncated or on two lines, better would be to have just the logo and the word "Community"... is that possible just for the menu, but still have "NOI Community" for the app name in general

**Comment by Piiit** [comment]
Here it is on Android.... Since we already have "NOI" in the icon, it would be nice to just call it "Community" underneath... if that is possible at all and still keep the Store name "NOI Community"?

![appmenu](https://user-images.githubusercontent.com/6096063/142011292-15085b76-cfd9-48a4-bdb3-1dade0d1b8e3.png)

**Comment by chiaraDimension** [comment]
Ok, we can try to change it, but for iOS version we have to see if Apple will accept it.

**Comment by Piiit** [comment]
Works, thx
