### ISSUE TITLE
New parameter "optimizedates" available

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.noi.community.android#79]
The api Endpoints EventShort and EventShort/{id} now have a new parameter called `optimizedates`.
By passing `optimizedates=true` there are done some checks on api side:
- Filtering out all rooms which should not displayed in the App (from Array Roombooked)
- Checking if Startdate/Enddate of the Event is in line with the first Startdate + last Enddate of the Rooms available

**Comment by matax87** [comment]
@RudiThoeni the new parameters has been added without any problem. Does exist any way to test it? 

Thank you!

**Comment by RudiThoeni** [comment]
at example for Id: "**eventshort-17926**"
`https://tourism.opendatahub.bz.it/v1/EventShort?startdate=1638261192823&eventlocation=NOI&datetimeformat=uxtimestamp&onlyactive=true`
there are currently 5 rooms into Roombooked, two of them are marked with x which means they should not displayed
Start and Enddate is set to
```
2021-11-30T12:00:00  
2021-12-03T12:00:00
```

after applying the parameter
`https://tourism.opendatahub.bz.it/v1/EventShort?startdate=1638261192823&eventlocation=NOI&datetimeformat=uxtimestamp&onlyactive=true&optimizedates=true`

Roombooked has only 3 rooms inside and the start+ enddate of the event is set to begindate of the first room booked, enddate of the last room booked
```
StartDate: "2021-12-01T13:00:00",
EndDate: "2021-12-02T14:00:00",
```

**Comment by matax87** [comment]
> at example for Id: "**eventshort-17926**" `https://tourism.opendatahub.bz.it/v1/EventShort?startdate=1638261192823&eventlocation=NOI&datetimeformat=uxtimestamp&onlyactive=true` there are currently 5 rooms into Roombooked, two of them are marked with x which means they should not displayed Start and Enddate is set to
> 
> ```
> 2021-11-30T12:00:00  
> 2021-12-03T12:00:00
> ```
> 
> after applying the parameter `https://tourism.opendatahub.bz.it/v1/EventShort?startdate=1638261192823&eventlocation=NOI&datetimeformat=uxtimestamp&onlyactive=true&optimizedates=true`
> 
> Roombooked has only 3 rooms inside and the start+ enddate of the event is set to begindate of the first room booked, enddate of the last room booked
> 
> ```
> StartDate: "2021-12-01T13:00:00",
> EndDate: "2021-12-02T14:00:00",
> ```

At this time we are not using `Roombooked`. Is this supposed to be an update for future iterations of the app?

**Comment by RudiThoeni** [comment]
As far as i know the proposal for displaying events in the future is this:
-on the tiles view: display start + enddate of the events
-in the detail view of the event display the Information of Roombooked (means each day start + enddate)

@MarE1991 i don´t know in which iteration this plan will be implemented....  i think when it was not communicated yet it will be in the future iterations,

**Comment by Piiit** [comment]
@matax87 @RudiThoeni @MarE1991 Works, thx
