### ISSUE TITLE
As a NOI community manager I want the Open Data Hub Authentication integrated in the Android version of the NOI App.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.noi.community.android#83]

**Comment by chiaraDimension** [comment]
@MarE1991 @pkritzinger 
We need the texts to use in authentication wizard:

<img width="375" alt="page1" src="https://user-images.githubusercontent.com/90265787/161706630-2a4abaf4-485c-44b6-85f2-a0274e63995e.png">

![page2](https://user-images.githubusercontent.com/90265787/161706626-93af74eb-cf9c-48e7-8ccd-526b31add98b.png)

![page3](https://user-images.githubusercontent.com/90265787/161706621-3364a468-7a4c-4a43-84f7-bf29ac923659.png)

**Comment by chiaraDimension** [comment]
@sseppi could you provide us the URL to sign up page?

How does the flow "post sign up" work? Will we already have an active session? Or will we have to go through OAuth login?

**Comment by sseppi** [comment]
@chiaraDimension the workflow is the same as for the testing enviroment that Peter shared with you in the past weeks.

**Comment by MarE1991** [comment]
> @MarE1991 @pkritzinger We need the texts to use in authentication wizard:
> 
> <img alt="page1" width="375" src="https://user-images.githubusercontent.com/90265787/161706630-2a4abaf4-485c-44b6-85f2-a0274e63995e.png">
> 
> ![page2](https://user-images.githubusercontent.com/90265787/161706626-93af74eb-cf9c-48e7-8ccd-526b31add98b.png)
> 
> ![page3](https://user-images.githubusercontent.com/90265787/161706621-3364a468-7a4c-4a43-84f7-bf29ac923659.png)

@chiaraDimension I'll provide the texts in the three languages tomorrow.

**Comment by Piiit** [comment]
@chiaraDimension I wrote you inside the other issue, hope that solves this issue as well

**Comment by MarE1991** [comment]
@chiaraDimension here we go with the texts: 
[Onboarding Texte App.docx](https://github.com/noi-techpark/it.bz.noi.community.android/files/8427186/Onboarding.Texte.App.docx)

**Comment by chiaraDimension** [comment]
> @chiaraDimension here we go with the texts:
> [Onboarding Texte App.docx](https://github.com/noi-techpark/it.bz.noi.community.android/files/8427186/Onboarding.Texte.App.docx)

Could you please add them to the[ Google Sheet](https://docs.google.com/spreadsheets/d/1Yiol3UqS-0I9q4R5HLifVMdGbTSe3ZwuYBAMPyZJthc/edit#gid=0)? There are also some other cells to fill

**Comment by MarE1991** [comment]
> > @chiaraDimension here we go with the texts:
> > [Onboarding Texte App.docx](https://github.com/noi-techpark/it.bz.noi.community.android/files/8427186/Onboarding.Texte.App.docx)
> 
> Could you please add them to the[ Google Sheet](https://docs.google.com/spreadsheets/d/1Yiol3UqS-0I9q4R5HLifVMdGbTSe3ZwuYBAMPyZJthc/edit#gid=0)? There are also some other cells to fill

@chiaraDimension ok, done! Let me know if there are other cells to fill.

**Comment by chiaraDimension** [comment]
@pkritzinger we noticed that, depending of screen size, the texts in onboarding wizard can become unreadable: when title and description are placed about in the middle of the screen, the background is too light.

![Screenshot_20220414_120703](https://user-images.githubusercontent.com/90265787/163368095-7b1a0179-d941-4ffe-b51c-7970a7a3446b.png)

**Comment by pkritzinger** [comment]
hi @chiaraDimension . thanks.  i would suggest that we provide a new dark-transparent layer. we'll update the design respectively.

**Comment by pkritzinger** [comment]
@chiaraDimension : screens have been updated in the XD-file we shared with you.
